#!/usr/bin/env python3
"""Build the western terrain: the Urubamba gorge and Machu Picchu.

This mesh picks up exactly where the corridor leaves off, at -72.34, and runs
28 km west to the citadel. It exists because of what an earlier split got
wrong: Machu Picchu shipped as an island 16 km clear of the corridor, on the
theory that the gorge between them was terrain nobody would look at. The camera
flies straight over it, so the hole was in frame for the whole crossing, and no
amount of haze on top of a hole makes it ground.

Two things make the join work rather than merely touch.

The first is the shared coordinate system: like every builder here, this one
projects through `terrain_common`, anchored on the corridor's centre and
measured from one datum, so the vertices come out where this ground really is
and the model loads at the identity transform.

The second is `align_to_corridor`. Sharing a bounding edge is not sharing a
surface — two grids resampling the same DEM independently disagree either side
of the seam and open a hairline crack the height of the valley wall. So this
area is snapped onto the corridor's own lattice: its eastern column *is* the
corridor's western column, and its rows step at the corridor's row spacing.
Every shared vertex is then the same sample of the same data.

Sampling therefore matches the corridor's ~54 m rather than the ~19 m the
citadel alone used to get. That is not a loss: the camera is aerial now, 4 to
8 km out, and at that range the corridor's own sampling is what the drape can
carry anyway.

Run: `python3 scripts/build-west-terrain-glb.py`

Needs Pillow, numpy, and `bunx` for Draco compression.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from terrain_common import (  # noqa: E402
    ATTRIBUTION,
    DEM_URL,
    DEM_ZOOM,
    IMAGERY_URL,
    IMAGERY_ZOOM,
    METERS_PER_UNIT,
    ROOT,
    SEA_LEVEL,
    Projection,
    align_to_corridor,
    bake_texture,
    build_mesh,
    compress_with_draco,
    decode_terrarium,
    fetch_mosaic,
    sample_grid,
    split_primitives,
    versioned_url,
    write_glb,
)

# West to the citadel, and far enough north and south that the frame has ground
# in it wherever the tour looks. The eastern edge is not given: it is fixed at
# the corridor's, because that is the whole point of this mesh.
#
# The exact box comes back from `align_to_corridor`, which nudges these onto
# the lattice. Nothing downstream should re-derive it.
WEST_LON = -72.60
NORTH_LAT = -13.10
SOUTH_LAT = -13.38

WEST_TERRAIN_AREA, GRID_COLS, GRID_ROWS = align_to_corridor(
    WEST_LON, NORTH_LAT, SOUTH_LAT
)

# ~14 m per texel across 28 km, which matches the corridor's ~15 m. Going finer
# would make the seam the sharpest thing in the frame.
TEXTURE_WIDTH = 2048
TEXTURE_QUALITY = 82

DRACO_QUANTIZE = {"position": 14, "normal": 10, "texcoord": 12}

GLB_OUT = ROOT / "public" / "models" / "west-terrain.glb"
PLACE_OUT = ROOT / "components" / "landing" / "west-terrain-place.ts"


def write_place_module(projection: Projection) -> None:
    """Emit the mesh's scene extent, for the runtime's lazy load."""
    x_min, z_min, x_max, z_max = projection.bounds()
    PLACE_OUT.write_text(
        f'''/**
 * Generated by `scripts/build-west-terrain-glb.py`. Do not edit by hand.
 *
 * Scene units shared with `sacred-valley-place.ts`. The western terrain is
 * authored at its true offset from the Sacred Valley origin and snapped onto
 * the corridor's sampling lattice, so it loads at the identity transform and
 * meets the corridor without a seam. It needs no placing.
 */

export const WEST_TERRAIN_GLB = "{versioned_url(GLB_OUT, "/models/west-terrain.glb")}";

/** Scene-space extent, as [xMin, zMin, xMax, zMax]. */
export const WEST_TERRAIN_EXTENT = [
  {x_min:.3f}, {z_min:.3f}, {x_max:.3f}, {z_max:.3f},
] as const;

/** Geographic bounding box, as [west, south, east, north]. */
export const WEST_TERRAIN_BBOX = [
  {WEST_TERRAIN_AREA.lon_west:.6f}, {WEST_TERRAIN_AREA.lat_south:.6f}, {WEST_TERRAIN_AREA.lon_east:.6f}, {WEST_TERRAIN_AREA.lat_north:.6f},
] as const;
'''
    )
    print(f"wrote {PLACE_OUT.relative_to(ROOT)}")


def main() -> None:
    dem_mosaic, dem_x0, dem_y0 = fetch_mosaic(
        DEM_URL, WEST_TERRAIN_AREA, DEM_ZOOM, "elevation"
    )
    dem = decode_terrarium(dem_mosaic)

    # Deliberately the shared datum, not this mosaic's own floor. The gorge
    # bottoms out below the Sacred Valley's lowest ground, so these heights go
    # negative — which is correct, the river really is lower here.
    projection = Projection(
        WEST_TERRAIN_AREA, dem_x0, dem_y0, DEM_ZOOM, sea_level=SEA_LEVEL
    )
    x_min, z_min, x_max, z_max = projection.bounds()
    print(
        f"terrain {projection.width_units:.1f} x {projection.depth_units:.1f} units "
        f"({projection.width_units * METERS_PER_UNIT / 1000:.1f} x "
        f"{projection.depth_units * METERS_PER_UNIT / 1000:.1f} km), "
        f"elevation {dem.min():.0f}-{dem.max():.0f} m"
    )
    print(
        f"scene extent x {x_min:.1f}..{x_max:.1f}, z {z_min:.1f}..{z_max:.1f}; "
        f"grid {GRID_COLS} x {GRID_ROWS} at "
        f"{projection.width_units * METERS_PER_UNIT / GRID_COLS:.0f} m"
    )

    imagery, _, _ = fetch_mosaic(
        IMAGERY_URL, WEST_TERRAIN_AREA, IMAGERY_ZOOM, "imagery"
    )

    elevations = sample_grid(dem, projection, GRID_COLS, GRID_ROWS)
    positions, normals, uvs = build_mesh(
        elevations, projection, GRID_COLS, GRID_ROWS
    )
    chunks = split_primitives(positions, normals, uvs, GRID_COLS, GRID_ROWS)
    texture = bake_texture(
        imagery, WEST_TERRAIN_AREA, TEXTURE_WIDTH, TEXTURE_QUALITY
    )
    write_glb(
        GLB_OUT,
        chunks,
        texture,
        WEST_TERRAIN_AREA,
        name="west-terrain",
        title="Urubamba Gorge and Machu Picchu Terrain",
        hero_subject="terrain",
        material_name="west-terrain-surface",
    )
    compress_with_draco(GLB_OUT, DRACO_QUANTIZE)
    write_place_module(projection)
    print(f"\n{ATTRIBUTION}")


if __name__ == "__main__":
    main()
