// biome-ignore-all lint/suspicious/noApproximativeNumericConstant: these are
// terrain coordinates; one occasionally lands near a maths constant by chance.
/**
 * Generated by `scripts/build-sacred-valley-glb.py`. Do not edit by hand.
 *
 * Scene units shared with `public/models/sacred-valley.glb` and
 * `public/models/machu-picchu.glb`: one unit is 200 m on the ground,
 * heights carry a 2x exaggeration measured from a 2654 m datum, and
 * the origin sits at the centre of the Sacred Valley bounding box.
 */

export type ScenePoint = readonly [number, number, number];

/** Terrain extent in scene units. */
export const TERRAIN_SIZE = {
  width: 308.707,
  depth: 183.677,
} as const;

/** Geographic bounding box of the terrain, as [west, south, east, north]. */
export const TERRAIN_BBOX = [
  -72.34, -13.5, -71.77, -13.17,
] as const;

/** Cache-busting public URL: changes only when the mesh bytes change. */
/**
 * The mesh's public path, without the content stamp.
 *
 * Kept as its own constant so the stamped URL below can be checked against it:
 * the two have to agree, and a typo in either is otherwise a 404 that only
 * shows up as a hero that never draws. It used to live on the scene component
 * that mounted the flight, which is gone.
 */
export const SACRED_VALLEY_MODEL_PATH = "/models/sacred-valley.glb";

export const SACRED_VALLEY_GLB_URL = `${SACRED_VALLEY_MODEL_PATH}?v=3844d88dba`;

/** Metres of real ground per scene unit, for readouts that quote distances. */
export const METERS_PER_UNIT = 200;

/**
 * The Urubamba's course from Pisac down to Ollantaytambo, traced from the
 * elevation model by following the valley floor. Ordered downstream.
 */
export const URUBAMBA_PATH: readonly ScenePoint[] = [
  [113.219, 3.360, 47.573],
  [110.709, 3.267, 47.536],
  [108.199, 3.189, 47.481],
  [105.689, 3.130, 47.366],
  [103.180, 3.091, 47.116],
  [100.676, 3.064, 46.649],
  [98.180, 3.042, 45.897],
  [95.696, 3.023, 44.829],
  [93.242, 3.003, 43.435],
  [90.871, 2.982, 41.723],
  [88.662, 2.958, 39.734],
  [86.650, 2.933, 37.551],
  [84.763, 2.909, 35.299],
  [82.859, 2.891, 33.089],
  [80.842, 2.877, 30.957],
  [78.747, 2.863, 28.841],
  [76.699, 2.848, 26.654],
  [74.802, 2.831, 24.363],
  [73.029, 2.814, 21.979],
  [71.264, 2.794, 19.535],
  [69.410, 2.773, 17.058],
  [67.438, 2.754, 14.567],
  [65.352, 2.739, 12.076],
  [63.189, 2.727, 9.586],
  [61.026, 2.717, 7.098],
  [58.969, 2.708, 4.622],
  [57.094, 2.701, 2.218],
  [55.355, 2.697, 0.028],
  [53.598, 2.691, -1.747],
  [51.683, 2.678, -2.974],
  [49.566, 2.662, -3.693],
  [47.280, 2.648, -4.073],
  [44.885, 2.635, -4.326],
  [42.429, 2.621, -4.674],
  [39.942, 2.606, -5.311],
  [37.442, 2.592, -6.319],
  [34.938, 2.579, -7.586],
  [32.435, 2.567, -8.870],
  [29.938, 2.556, -9.954],
  [27.447, 2.549, -10.747],
  [24.956, 2.543, -11.246],
  [22.461, 2.533, -11.430],
  [19.960, 2.509, -11.201],
  [17.455, 2.466, -10.460],
  [14.947, 2.407, -9.249],
  [12.438, 2.345, -7.791],
  [9.929, 2.287, -6.363],
  [7.419, 2.237, -5.141],
  [4.909, 2.192, -4.129],
  [2.398, 2.152, -3.254],
  [-0.112, 2.120, -2.508],
  [-2.622, 2.096, -2.006],
  [-5.130, 2.077, -1.911],
  [-7.634, 2.062, -2.313],
  [-10.131, 2.051, -3.189],
  [-12.623, 2.041, -4.430],
  [-15.114, 2.032, -5.888],
  [-17.609, 2.021, -7.417],
  [-20.110, 2.012, -8.909],
  [-22.615, 2.012, -10.310],
  [-25.123, 2.027, -11.645],
  [-27.632, 2.054, -12.975],
  [-30.141, 2.080, -14.274],
  [-32.651, 2.088, -15.416],
  [-35.162, 2.079, -16.320],
  [-37.672, 2.058, -17.074],
  [-40.182, 2.029, -17.892],
  [-42.692, 1.996, -18.982],
  [-45.200, 1.963, -20.399],
  [-47.704, 1.934, -22.003],
  [-50.202, 1.906, -23.565],
  [-52.693, 1.879, -24.947],
  [-55.184, 1.853, -26.146],
  [-57.680, 1.833, -27.177],
  [-60.180, 1.819, -27.991],
  [-62.685, 1.811, -28.543],
  [-65.193, 1.799, -28.859],
  [-67.702, 1.779, -29.018],
  [-70.212, 1.750, -29.098],
  [-72.722, 1.718, -29.178],
  [-75.232, 1.687, -29.349],
  [-77.742, 1.660, -29.719],
  [-80.252, 1.638, -30.380],
  [-82.762, 1.623, -31.369],
  [-85.270, 1.614, -32.633],
  [-87.774, 1.609, -34.029],
  [-90.272, 1.601, -35.391],
  [-92.763, 1.588, -36.623],
  [-95.254, 1.571, -37.716],
  [-97.750, 1.553, -38.684],
  [-100.251, 1.538, -39.519],
  [-102.755, 1.532, -40.208],
  [-105.263, 1.555, -40.787],
  [-107.772, 1.628, -41.346],
  [-110.282, 1.759, -41.957],
  [-112.792, 1.920, -42.608],
] as const;

/** Towns along the corridor, in the same scene units. */
export const VALLEY_PLACES = {
  ollantaytambo: {
    label: "Ollantaytambo",
    position: [-112.813, 1.920, -42.604],
  },
  urubamba: {
    label: "Urubamba",
    position: [-33.579, 2.270, -17.285],
  },
  calca: {
    label: "Calca",
    position: [54.159, 2.680, -2.258],
  },
  pisac: {
    label: "Pisac",
    position: [113.192, 3.480, 47.566],
  },
} as const;

export type ValleyPlaceId = keyof typeof VALLEY_PLACES;

/**
 * The five sites the scroll stops at, in flight order.
 *
 * `elevation` is the published figure the landing copy quotes; the anchor's
 * own y is what the elevation model measured there, which differs by a few
 * tens of metres because one DEM pixel averages ~19 m of ground.
 *
 * `onTerrain` is false for Machu Picchu alone: it sits ~30 km beyond the
 * corridor mesh and ships as its own GLB, authored in these same units.
 */
export const SACRED_SITES = {
  pisac: {
    label: "P\u00edsac",
    position: [113.138, 5.820, 45.562],
    elevation: 2972,
    latitude: -13.4169,
    longitude: -71.8461,
    onTerrain: true,
  },
  moray: {
    label: "Moray",
    position: [-75.660, 8.540, -3.037],
    elevation: 3500,
    latitude: -13.3296,
    longitude: -72.1947,
    onTerrain: true,
  },
  maras: {
    label: "Salineras de Maras",
    position: [-54.322, 3.530, -22.126],
    elevation: 3000,
    latitude: -13.2953,
    longitude: -72.1553,
    onTerrain: true,
  },
  ollantaytambo: {
    label: "Ollantaytambo",
    position: [-112.813, 1.960, -42.827],
    elevation: 2792,
    latitude: -13.2581,
    longitude: -72.2633,
    onTerrain: true,
  },
  machupicchu: {
    label: "Machu Picchu",
    position: [-265.379, -2.155, -95.677],
    elevation: 2430,
    latitude: -13.1631,
    longitude: -72.545,
    onTerrain: false,
  },
} as const;

export type SacredSiteId = keyof typeof SACRED_SITES;

/**
 * The camera's tour of the five sites, solved against the elevation model.
 *
 * Every position here is guaranteed to stand in open air, and every station's
 * sight line to its subject is guaranteed to clear the ground by 0.7 units
 * (140 m). That is not a detail: half these sites sit against a
 * slope, Moray is 5 km off the river and 600 m above it, and the run out to
 * Machu Picchu crosses a 4,000 m cordillera. Solving it here, where the DEM is
 * in hand, is what keeps the runtime from having to raycast the terrain.
 *
 * `FLIGHT_PATH` and `FLIGHT_AIM` are parallel: the camera rides one and looks
 * at the other, so crossing between two sites turns the head rather than cuts.
 */
export const FLIGHT_PATH: readonly ScenePoint[] = [
  [127.503, 29.820, 85.029],
  [126.819, 28.397, 83.149],
  [126.135, 26.973, 81.270],
  [125.451, 25.550, 79.391],
  [124.767, 24.127, 77.511],
  [124.083, 22.703, 75.632],
  [123.399, 21.280, 73.753],
  [116.865, 22.166, 72.012],
  [110.331, 22.287, 70.271],
  [103.797, 21.868, 68.531],
  [97.263, 21.591, 66.790],
  [90.729, 21.445, 65.049],
  [84.196, 21.382, 63.309],
  [77.662, 21.361, 61.568],
  [71.128, 21.360, 59.828],
  [64.594, 21.379, 58.087],
  [58.060, 21.448, 56.346],
  [51.526, 21.590, 54.606],
  [44.992, 21.780, 52.865],
  [38.458, 21.618, 51.124],
  [31.925, 21.513, 49.384],
  [25.391, 21.461, 47.643],
  [18.857, 21.442, 45.903],
  [12.323, 21.439, 44.162],
  [5.789, 21.444, 42.421],
  [-0.745, 21.451, 40.681],
  [-7.279, 21.460, 38.940],
  [-13.813, 21.468, 37.199],
  [-20.346, 21.477, 35.459],
  [-26.880, 21.486, 33.718],
  [-33.414, 21.495, 31.978],
  [-39.948, 21.504, 30.237],
  [-46.482, 21.513, 28.496],
  [-53.016, 21.522, 26.756],
  [-59.550, 21.531, 25.015],
  [-66.084, 21.540, 23.274],
  [-62.641, 20.708, 19.780],
  [-59.199, 19.877, 16.285],
  [-55.756, 19.045, 12.790],
  [-52.314, 18.213, 9.295],
  [-48.871, 17.382, 5.800],
  [-45.429, 16.550, 2.306],
  [-50.575, 16.701, -1.042],
  [-55.722, 16.851, -4.389],
  [-60.868, 17.002, -7.736],
  [-66.015, 17.153, -11.083],
  [-71.161, 17.303, -14.431],
  [-76.308, 17.454, -17.778],
  [-81.454, 17.605, -21.125],
  [-86.600, 17.755, -24.472],
  [-93.163, 19.385, -26.720],
  [-99.725, 21.232, -28.968],
  [-106.287, 21.803, -31.216],
  [-112.849, 21.975, -33.464],
  [-119.411, 22.185, -35.712],
  [-125.973, 22.323, -37.960],
  [-132.535, 22.715, -40.208],
  [-139.097, 22.425, -42.456],
  [-145.659, 23.071, -44.704],
  [-152.221, 24.485, -46.952],
  [-158.783, 26.089, -49.200],
  [-165.345, 27.565, -51.448],
  [-171.907, 25.599, -53.696],
  [-178.470, 22.797, -55.944],
  [-185.032, 20.482, -58.191],
  [-191.594, 19.062, -60.439],
  [-198.156, 18.346, -62.687],
  [-204.718, 18.031, -64.935],
  [-211.280, 17.906, -67.183],
  [-217.842, 17.860, -69.431],
  [-224.404, 17.847, -71.679],
  [-230.966, 17.844, -73.927],
  [-237.528, 17.845, -76.175],
] as const;

export const FLIGHT_AIM: readonly ScenePoint[] = [
  [113.138, 5.820, 45.562],
  [113.138, 12.819, 45.562],
  [113.138, 17.178, 45.562],
  [113.138, 18.053, 45.562],
  [113.138, 15.649, 45.562],
  [113.138, 11.054, 45.562],
  [113.138, 5.820, 45.562],
  [104.178, 7.003, 43.255],
  [95.247, 8.177, 40.956],
  [86.373, 9.223, 38.672],
  [77.584, 10.203, 36.410],
  [68.907, 11.134, 34.176],
  [60.366, 12.011, 31.978],
  [51.986, 12.823, 29.820],
  [43.789, 13.559, 27.710],
  [35.794, 14.216, 25.652],
  [28.019, 14.805, 23.651],
  [20.478, 15.341, 21.710],
  [13.185, 15.808, 19.833],
  [6.147, 15.959, 18.021],
  [-0.628, 16.036, 16.277],
  [-7.139, 16.039, 14.601],
  [-13.384, 15.961, 12.994],
  [-19.367, 15.793, 11.454],
  [-25.094, 15.535, 9.979],
  [-30.574, 15.188, 8.569],
  [-35.820, 14.759, 7.218],
  [-40.845, 14.253, 5.925],
  [-45.669, 13.679, 4.683],
  [-50.309, 13.046, 3.489],
  [-54.789, 12.362, 2.336],
  [-59.132, 11.637, 1.218],
  [-63.363, 10.883, 0.128],
  [-67.510, 10.108, -0.939],
  [-71.599, 9.323, -1.992],
  [-75.660, 8.540, -3.037],
  [-70.823, 11.736, -7.364],
  [-66.330, 13.854, -11.384],
  [-62.430, 14.101, -14.872],
  [-59.217, 12.187, -17.747],
  [-56.598, 8.400, -20.090],
  [-54.322, 3.530, -22.126],
  [-64.319, 6.505, -25.665],
  [-73.908, 9.150, -29.058],
  [-82.741, 10.995, -32.184],
  [-90.586, 11.678, -34.961],
  [-97.364, 11.000, -37.359],
  [-103.154, 8.973, -39.408],
  [-108.188, 5.822, -41.190],
  [-112.813, 1.960, -42.827],
  [-121.940, 3.267, -45.988],
  [-131.019, 4.886, -49.134],
  [-140.007, 6.457, -52.247],
  [-148.859, 7.923, -55.313],
  [-157.534, 9.329, -58.318],
  [-165.993, 10.600, -61.249],
  [-174.203, 11.855, -64.093],
  [-182.135, 12.583, -66.840],
  [-189.764, 13.623, -69.483],
  [-197.071, 14.930, -72.014],
  [-204.045, 16.134, -74.430],
  [-210.678, 16.979, -76.728],
  [-216.971, 15.395, -78.908],
  [-222.930, 13.092, -80.972],
  [-228.568, 10.950, -82.925],
  [-233.903, 9.210, -84.773],
  [-238.960, 7.722, -86.525],
  [-243.767, 6.288, -88.190],
  [-248.359, 4.793, -89.781],
  [-252.773, 3.193, -91.310],
  [-257.052, 1.489, -92.792],
  [-261.239, -0.303, -94.242],
  [-265.379, -2.155, -95.677],
] as const;

/** Where each site falls along the flight, as an index into FLIGHT_PATH. */
export const FLIGHT_STATIONS = [
  { id: "overlook", index: 0 },
  { id: "pisac", index: 6 },
  { id: "moray", index: 35 },
  { id: "maras", index: 41 },
  { id: "ollantaytambo", index: 49 },
  { id: "machupicchu", index: 72 },
] as const;

/** Clearance the solver held, in scene units. */
export const SIGHT_CLEARANCE = 0.7;
