/**
 * Generated by `scripts/build-site-structures-glb.py`. Do not edit by hand.
 *
 * Terraces, towns, salt pans and the Six Monoliths, in the scene units the
 * terrain meshes share. Loads at the identity transform like everything else.
 */

export const SITE_STRUCTURES_GLB = "/models/site-structures.glb?v=d9969252d7";

/**
 * What the generator actually emitted, measured in real metres.
 *
 * The scene is anisotropic — 200 m per unit across, 100 m per unit up, since
 * the terrain carries a 2x vertical exaggeration — so a bounding box in scene
 * units says nothing on its own. These are converted per axis, which makes
 * them comparable against the published dimensions of the real sites and
 * therefore assertable in CI. A refactor that quietly halves a site shows up
 * as a failing test rather than as a screenshot someone notices months later.
 */
export const SITE_STRUCTURE_METRICS = {
  pisac: {
    triangles: 1026,
    widthM: 1032.3,
    depthM: 1032.1,
    reliefM: 384.2,
    reachM: 538.2,
  },
  moray: {
    triangles: 1536,
    widthM: 131.3,
    depthM: 130.0,
    reliefM: 30.0,
    reachM: 68.3,
  },
  maras: {
    triangles: 520,
    widthM: 387.1,
    depthM: 408.7,
    reliefM: 182.1,
    reachM: 211.9,
  },
  ollantaytambo: {
    triangles: 1180,
    widthM: 1014.9,
    depthM: 867.8,
    reliefM: 74.0,
    reachM: 538.1,
  },
  machupicchu: {
    triangles: 716,
    widthM: 1072.3,
    depthM: 946.8,
    reliefM: 364.0,
    reachM: 548.0,
  },
} as const;
