/**
 * Generated by `scripts/build-west-terrain-glb.py`. Do not edit by hand.
 *
 * Scene units shared with `sacred-valley-place.ts`. The western terrain is
 * authored at its true offset from the Sacred Valley origin and snapped onto
 * the corridor's sampling lattice, so it loads at the identity transform and
 * meets the corridor without a seam. It needs no placing.
 */

export const WEST_TERRAIN_GLB = "/models/west-terrain.glb?v=93ee37e6d2";

/** Scene-space extent, as [xMin, zMin, xMax, zMax]. */
export const WEST_TERRAIN_EXTENT = [
  -295.162, -130.987, -154.353, 25.071,
] as const;

/** Geographic bounding box, as [west, south, east, north]. */
export const WEST_TERRAIN_BBOX = [
  -72.599991, -13.380096, -72.340000, -13.099606,
] as const;
